### ISSUE TITLE
Naming convention with "Directive" and "Object" (deprecated) still needed

### ISSUE THREAD

**Issue by isto2278** [isto2278/Threedom#5]
There should not be a need for a naming convention like MVC, classes should be found no matter their name as long as they're in the correct directories.

**Comment by TimPietsch** [comment]
Fixed for objects

**Comment by TimPietsch** [comment]
Directives as used right now are questionable anyway. Maybe use just for logic/data queries and allow only two html outputs: There application/front and the configuration/back?

**Comment by isto2278** [comment]
The HTML backend has been put on hold, it's not needed for first alpha and beta versions.

**Comment by isto2278** [comment]
Naming convention was mostly removed in latest commit to new-core-structure and will be removed with the merge.

**Comment by isto2278** [comment]
Closing this right now, as it'll be resolved with the merge.
